version: "3.3"

services:

  auth:
    build:
      context: .
    image: auth-node
    env_file: docker-compose.env
    environment:
      SERVICES: AUTH
    depends_on:
      - mongodb
    ports:
      - 3001:3000
    networks:
      - internal
    restart: always

  todo:
    build:
      context: .
    image: todo-node
    env_file: docker-compose.env
    environment:
      SERVICES: TODO
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    networks:
      - internal
    restart: always

  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    networks:
      - internal

networks:
  internal: